diaryList:
  caption:
    ja_JP: "全体の最新外部公開日記"
  description:
    ja_JP: "全体の外部公開日記を新着順に表示します。"
  component: [portal, diaryList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10

recentCommunityTopic:
  caption:
    ja_JP: "最新トピックリスト"
  description:
    ja_JP: "全体の最新コミュニティトピックを表示します"
  component: [portal, topicList]
  config:
    col:
      Name:       "col"
      Caption:    "表示するトピック数"
      FormType:   "select"
      ValueType:  "integer"
      IsRequired: true
      Default:    5
      Choices:    {1: 1, 3: 3, 5: 5, 7: 7, 10: 10}

recentCommunityEvent:
  caption:
    ja_JP: "最新イベントリスト"
  description:
    ja_JP: "全体の最新コミュニティイベントを表示します"
  component: [portal, eventList]
  config:
    col:
      Name:       "col"
      Caption:    "表示するイベント数"
      FormType:   "select"
      ValueType:  "integer"
      IsRequired: true
      Default:    5
      Choices:    {1: 1, 3: 3, 5: 5, 7: 7, 10: 10}

albumList:
  caption:
    ja_JP: "全体の最新外部公開アルバム"
  description:
    ja_JP: "全体の外部公開アルバムを新着順に表示します。"
  component: [portal, albumList]
  config:
    max:
      Name:      "max"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        1: 1
        3: 3
        5: 5
        7: 7
        10: 10